#!/usr/bin/env python3

import random
import string
import sys

### Input

input_option = int(input("Input from:\n1) File\n2) Enter message\n"))

if input_option == 1:
    input_file = input("File to input: ")
    with open(input_file, 'r') as fr:
        message_input = fr.read()
elif input_option == 2:
    message_input = input("Enter message: ")

### Encryption

random.seed(input("Key: "))

characters_scrambled = ''.join(random.sample(string.printable,len(string.printable)))

crypt_option = int(input("1) Encrypt\n2) Decrypt\n"))

message_output = ""
abort_check = 0

for char in message_input:
    if char in string.printable:
        if crypt_option == 1:
            message_output += characters_scrambled[string.printable.index(char)]
        elif crypt_option == 2:
            message_output += string.printable[characters_scrambled.index(char)]
    else:
        print("Invalid character: " + char)
        abort_check += 1

### Output

if abort_check > 0:
    sys.exit()

print(message_output)

output_file = input("File to output: ")

if len(output_file) > 0:
    with open(output_file, 'w') as fw:
        fw.write(message_output)
